name: 🛠️ Build & Publish Custom Chip

on:
  push:
    paths:
      - 'src/**'
      - 'chip.json'
      - '.github/workflows/**'
      - 'wokwi.toml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clean previous WASM
        run: rm -f *.wasm

      - name: Debug before build
        run: |
          echo "== Before build =="
          ls -R .

      - name: Build WASM
        uses: wokwi/wokwi-chip-clang-action@main
        with:
          sources: src/main.c

      - name: Debug after build
        run: |
          echo "== After build =="
          ls -R .
          
      - name: Check dist content and permissions
        run: ls -l dist/

      - name: Fix permissions and rename output files
        run: |
          CHIP_ID=$(jq -r .name chip.json)
          sudo chown -R runner:runner dist
          cp dist/chip.wasm "dist/${CHIP_ID}.chip.wasm"
          cp chip.json "dist/${CHIP_ID}.chip.json"

      - name: Commit dist files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ github.ref_name }}
          file_pattern: 'dist/*'
          commit_message: '📦 Add compiled WASM and chip.json to dist/'
