name: 🛠️ Build & Publish Custom Chip

on:
  push:
    paths:
      - 'src/**'
      - 'chip.json'
      - '.github/workflows/**'
      - 'wokwi.toml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clean previous WASM
        run: rm -f *.wasm

      - name: Debug before build
        run: |
          echo "== Before build =="
          ls -R .

      - name: Build WASM
        uses: wokwi/wokwi-chip-clang-action@main
        with:
          sources: src/main.c

      - name: Debug after build
        run: |
          echo "== After build =="
          ls -R .

      - name: Prepare dist directory
        run: |
          mkdir -p dist
          mv chip.wasm dist/ads1115.chip.wasm
          cp chip.json dist/ads1115.chip.json

      - name: Commit dist files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ github.ref_name }}
          file_pattern: 'dist/*'
          commit_message: '📦 Add compiled WASM and chip.json to dist/'
