name: Build Chip
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build WASM
        uses: wokwi/wokwi-chip-clang-action@main
        with:
          sources: src/main.c
      - name: Prepare dist
        run: |
          mkdir -p dist
          mv *.wasm dist/${{ github.event.repository.name }}.chip.wasm
          cp chip.json dist/${{ github.event.repository.name }}.chip.json
      - name: Push dist
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: dist/*
          commit_message: 'Add dist files'
          branch: ${{ github.ref_name }}
